name: family_speed_selector
description: Family Speed Selector made with Flutter
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/clock.svg
    - assets/icons/fire.svg
    - assets/icons/lightning.svg

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
